SELECT * FROM project.customer_t
-- Find the total number of unique customers who have placed orders
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM order_t;

-- Distribution of customers across states
SELECT 
    c.state, COUNT(DISTINCT o.customer_id) AS customers_in_state
FROM
    customer_t c
        JOIN
    order_t o ON c.customer_id = o.customer_id
GROUP BY c.state
ORDER BY customers_in_state DESC;

--Question 2: Which are the top 5 vehicle makers preferred by the customers?
SELECT 
    p.vehicle_maker, 
    COUNT(DISTINCT o.customer_id) AS number_of_customers
FROM 
    product_t p
JOIN 
    order_t o ON p.vehicle_model = (
        SELECT vehicle_model FROM product_t WHERE product_id = o.product_id
    )
GROUP BY 
    p.vehicle_maker
ORDER BY 
    number_of_customers DESC
LIMIT 5;

--Question 3: Which is the most preferred vehicle maker in each state?
SELECT 
    c.state,
    p.vehicle_maker,
    COUNT(DISTINCT o.customer_id) AS customer_count
FROM 
    order_t o
JOIN 
    product_t p ON o.product_id = p.product_id
JOIN
    customer_t c ON o.customer_id = c.customer_id
GROUP BY 
    c.state, p.vehicle_maker
HAVING 
    COUNT(DISTINCT o.customer_id) = (
        SELECT MAX(sub_counts.customer_count)
        FROM (
            SELECT 
                c2.state,
                p2.vehicle_maker,
                COUNT(DISTINCT o2.customer_id) AS customer_count
            FROM 
                order_t o2
            JOIN 
                product_t p2 ON o2.product_id = p2.product_id
            JOIN
                customer_t c2 ON o2.customer_id = c2.customer_id
            WHERE c2.state = c.state
            GROUP BY c2.state, p2.vehicle_maker
        ) AS sub_counts
        WHERE sub_counts.state = c.state
    );
    
   -- 4 Find the overall average rating given by the customers. What is the average rating in each quarter? 
    WITH feedback_mapping AS (
    SELECT
        order_id,
        -- Map feedback categories to numerical values
        CASE
            WHEN customer_feedback = 'Very Bad' THEN 1
            WHEN customer_feedback = 'Bad' THEN 2
            WHEN customer_feedback = 'Okay' THEN 3
            WHEN customer_feedback = 'Good' THEN 4
            WHEN customer_feedback = 'Very Good' THEN 5
            ELSE NULL -- Handle unexpected values
        END AS feedback_value,
        -- Extract quarter and year from order_date
        EXTRACT(QUARTER FROM order_date) AS quarter_number,
        EXTRACT(YEAR FROM order_date) AS year
    FROM order_t
)
SELECT
    -- Overall average rating
    AVG(feedback_value) AS overall_average_rating,
    -- Average rating per quarter
    CONCAT('Q', quarter_number, ' ', year) AS quarter,
    AVG(feedback_value) AS average_rating_in_quarter
FROM feedback_mapping
GROUP BY year, quarter_number
ORDER BY year, quarter_number;

--Question 5: Find the percentage distribution of feedback from the customers. Are customers getting more dissatisfied over time?
SELECT
    o.customer_feedback,
    COUNT(*) AS feedback_count,
    ROUND(COUNT(*) * 100.0 / t.total_count, 2) AS percentage
FROM
    order_t o
JOIN
    (SELECT COUNT(*) AS total_count FROM order_t) AS t
GROUP BY
    o.customer_feedback, t.total_count;
--Are customers getting more dissatisfied over time?

SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS feedback_month,
    COUNT(*) AS total_feedback,
    SUM(CASE WHEN customer_feedback IN ('Bad', 'Very Bad') THEN 1 ELSE 0 END) AS dissatisfied_count,
    ROUND(
        SUM(CASE WHEN customer_feedback IN ('Bad', 'Very Bad') THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS dissatisfaction_percentage
FROM
    order_t
GROUP BY
    feedback_month
ORDER BY
    feedback_month;
    
--Question 6: What is the trend of the number of orders by quarter?
SELECT
    CONCAT('Q', quarter_number, ' ', year) AS quarter,
    COUNT(order_id) AS total_orders
FROM (
    SELECT
        order_id,
        EXTRACT(QUARTER FROM order_date) AS quarter_number,
        EXTRACT(YEAR FROM order_date) AS year
    FROM order_t
) AS sub
GROUP BY year, quarter_number
ORDER BY year, quarter_number;

--Question 7: Calculate the net revenue generated by the company. What is the quarter-over-quarter % change in net revenue?
WITH quarterly_revenue AS (
    SELECT
        quarter_number,
        SUM(quantity * vehicle_price * (1 - discount)) AS total_net_revenue
    FROM
        order_t
    GROUP BY
        quarter_number
),
revenue_change AS (
    SELECT
        a.quarter_number,
        a.total_net_revenue,
        LAG(a.total_net_revenue) OVER (ORDER BY a.quarter_number) AS previous_quarter_revenue
    FROM
        quarterly_revenue a
)
SELECT
    quarter_number,
    total_net_revenue,
    CASE
        WHEN previous_quarter_revenue IS NULL THEN NULL
        ELSE ((total_net_revenue - previous_quarter_revenue) / previous_quarter_revenue) * 100
    END AS qoq_percentage_change
FROM
    revenue_change;

--Question 8: What is the trend of net revenue and orders by quarters?

    
WITH quarterly_data AS (
    SELECT
        EXTRACT(YEAR FROM order_date) AS year,
        EXTRACT(QUARTER FROM order_date) AS quarter,
        SUM(quantity * vehicle_price * (1 - discount)) AS total_net_revenue,
        COUNT(*) AS total_orders
    FROM
        order_t
    GROUP BY
        year,
        quarter
    ORDER BY
        year,
        quarter
)
SELECT
    year,
    quarter,
    total_net_revenue,
    total_orders
FROM
    quarterly_data
--Question 9: What is the average discount offered for different types of credit cards?
SELECT
    c.credit_card_type,
    AVG(o.discount) AS average_discount
FROM
    order_t o
JOIN
    customer_t c ON o.customer_id = c.customer_id
GROUP BY
    c.credit_card_type
    
--Question 10: What is the average time taken to ship the placed orders for each quarter?
SELECT
    QUARTER(order_date) AS quarter,
    YEAR(order_date) AS year,
    AVG(DATEDIFF(ship_date, order_date)) AS average_shipping_time_days
FROM
    order_t
GROUP BY
    year,
    quarter
ORDER BY
    year,
    quarter;

==1. Total Revenue

SELECT SUM(vehicle_price * quantity - discount) AS total_revenue
FROM order_t;

--2. Total Orders
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM order_t;
--3. Total Customers
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM order_t;
--4. Average Rating
SELECT AVG(
    CASE customer_feedback
        WHEN 'Very Bad' THEN 1
        WHEN 'Bad' THEN 2
        WHEN 'Okay' THEN 3
        WHEN 'Good' THEN 4
        WHEN 'Very Good' THEN 5        ELSE NULL
    END
) AS average_rating
FROM order_t
WHERE customer_feedback IS NOT NULL;
--5. Last Quarter Revenue
SELECT
    SUM(quantity * vehicle_price * (1 - discount/100)) AS last_quarter_revenue
FROM
    order_t
WHERE
    DATE_FORMAT(order_date, '%Y-%m') = DATE_FORMAT(DATE_SUB(CURRENT_DATE, INTERVAL 3 MONTH), '%Y-%m');
--7. Average Days to Ship
SELECT AVG(DATEDIFF(ship_date, order_date)) AS average_days_to_ship
FROM order_t
WHERE ship_date IS NOT NULL;
--% Good Feedback
SELECT
    (SUM(CASE WHEN customer_feedback = 'Good' THEN 1 ELSE 0 END) * 100.0) / COUNT(*) AS percent_good_feedback
FROM order_t
WHERE customer_feedback IS NOT NULL;